### PR TITLE
added tests for event search

### PR DESCRIPTION
**Pull request by ayhchen13**
Added tests for event search but unable to run on my computer current due to setup issues. Will resolve asap. Also deleted the python file and search_results.html since they're not used at all.

### CODE REVIEW

**Review by Jared-Waldroff — CHANGES_REQUESTED** [review]
Adams, I see that all the python files in the python directory are getting deleted in this, why is that?

**Comment by Jared-Waldroff** [comment]
Went over deletion of Python directory with Adams and Kaycee and both approved that it's ok to delete.

**Comment by AngryMagnets** [comment]
Yeah those are the python files we deleted before but I think they got reintroduced because someone didn't merge main into their branch

**Comment by BryceD-4** [comment]
Test pages look good! I agree with getting rid of those python files as well.

**Review by AngryMagnets — APPROVED** [review]
Looks good, these pythin files got reintroduced from another branch so deleting them is fine

**Review by Jared-Waldroff — APPROVED** [review]
Approved deletion of python files

**Pull request merged**
