### PR TITLE
Jared Final Fixes

### PR DESCRIPTION
**Pull request by Jared-Waldroff**
Cleaned up unused code
Removed old comments
Refactored some of the lines in header and footer so each html is cleaner
Fixed issue with registration and viewing tickets
When an event is updated it now redirects you to the event approval page where you can see the event you just created

### CODE REVIEW

**Review by ayhchen13 — APPROVED** [review]
Checked all the updates and everything working properly. I was gonna fix the event approval thing and saw that you fixed it. Thank you!

**Comment by Jared-Waldroff** [comment]
Don't pull yet

**Comment by Jared-Waldroff** [comment]
Good to pull

**Review by AngryMagnets — APPROVED** [review]
Looks Good! (my final one :') )

**Pull request merged**
