### PR TITLE
Navbar Completion

### PR DESCRIPTION
**Pull request by Jared-Waldroff**
I've completed the navbar and the functionality to move across the website cleanly. I updated all pages to include the navbar. Added back in loginandregistration page as I saw it was gone for somereason.  Also got rid of styleguide function in app.py. I'm having an issue verifying the user and displaying the profile text instead of login. I had it working at one point but then it broke. Going to do more debuging to find the issue.

### CODE REVIEW

**Comment by ayhchen13** [comment]
Navbar looks great! All buttons linking to correct pages. I believe evententry.html is missing the navbar tho.

**Comment by Jared-Waldroff** [comment]
Yes adding things to the navbar is super easy and we can do that later. Main thing is that it is on all pages and works. Still adjusting log in feature though.

**Comment by Jared-Waldroff** [comment]
Just pushed those changes

**Review by AngryMagnets — COMMENTED** [review]
Looks good

**Pull request merged**
