### PR TITLE
Jared Fix Navbar Login & App Appearence

### PR DESCRIPTION
**Pull request by Jared-Waldroff**
Had to adjust navbar to take in new CurrentUser variable to work properly. Made each page look consistent with headers and  titles. Added footer to all pages. Got rid of not needed code in hostentry. Finished host entry html with form to enter in new location. Updated login to be more consistent with other pages. Next step is having the users tickets be displayed for their events on their profile.

### CODE REVIEW

**Comment by Jared-Waldroff** [comment]
Updated the lines that show up in the terminal once the app is running so instead of typing in localhost:5001 you can click the link.

**Comment by Jared-Waldroff** [comment]
Changed it so when you register it logs you in and takes you to the account page.

**Review by AngryMagnets — APPROVED** [review]
Everything looks good

**Comment by BryceD-4** [comment]
Looks good, good use of comments and commits. I didn't know what favicon was, that's really cool! I don't see any conflicts or issues.

**Pull request merged**
